Revamp run-demo; add collect-logs, logs/*-wsl.log
Now `run-demo` can be executed in `--debug` or `--strace` mode, and
shuts the web server down more cleanly thanks to using an EXIT trap.

`collect-logs` automatically runs `run-demo` multiple times to capture
four permutations of the logs (`--debug` or `--strace`, with and without
`--no-ws`). The strace logs are heavily edited to show the activity near
the point of the successful page load (`strace-no-websocket-wsl.log`) or
the crash (`strace-wsl.log`).

The previous `logs/*-ubuntu1704.txt` logs have been removed and will be
regenerated in the next commit.

diff --git a/run-demo b/run-demo
--- a/run-demo
+++ b/run-demo
@@ -1,26 +1,78 @@
 #! /usr/bin/env bash
+#
+# Recreates the PhantomJS 2.1.1 WebSocket crash on Windows Subsystem for Linux
+#
+# Usage:
+#   run-demo [--no-ws|--debug|--strace]
+#
+# Flags:
+#   --no-ws         Run http-server instead of live-server to disable WebSockets
+#   --debug         Run PhantomJS in debug mode
+#   --strace        Run PhantomJS under strace
+#
+# To recreate the failure, an empty index.html page is served via `live-server`,
+# which injects JavaScript to open a WebSocket back to the server in order to
+# notify the browser of updates.
+#
+# Only one of --debug or --strace may be specified at a time.
+
+declare DEMO_ROOTDIR="${0%/*}"
+declare NO_WS
+declare PHANTOMJS_DEBUG
+declare STRACE_PHANTOMJS
+declare PHANTOMJS='node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs'
+declare PHANTOMJS_CMD=("$PHANTOMJS")
+
+if ! cd "$DEMO_ROOTDIR"; then
+  printf "Couldn't change to %s; exiting.\n" "$DEMO_ROOTDIR" >&2
+  exit 1
+fi
+DEMO_ROOTDIR="$PWD"
 
 if ! command -v node >/dev/null; then
   printf 'Install Node.js to run this demo: https://nodejs.org\n' >&2
   exit 1
-elif [[ ! -d './node_modules' ]]; then
-  npm install || exit 1
+elif [[ ! -d './node_modules' ]] && ! npm install; then
+  printf '`npm install` failed; exiting.\n' >&2
+  exit 1
+fi
+
+while [[ "$#" -ne '0' ]]; do
+  case "$1" in
+  --no-ws)
+    NO_WS='true'
+    ;;
+  --debug)
+    PHANTOMJS_DEBUG='true'
+    PHANTOMJS_CMD=("$PHANTOMJS" '--debug=true')
+    ;;
+  --strace)
+    STRACE_PHANTOMJS='true'
+    PHANTOMJS_CMD=('strace' "$PHANTOMJS")
+    ;;
+  *)
+    printf 'Unknown argument: %s\n' "$1" >&2
+    exit 1
+  esac
+  shift
+done
+
+if [[ "$PHANTOMJS_DEBUG" == 'true' && "$STRACE_PHANTOMJS" == 'true' ]]; then
+  printf 'Only one of --debug or --strace can be specified.\n' >&2
+  exit 1
 fi
 
 set -m
 
-if [[ "$1" == '--no-ws' ]]; then
+if [[ "$NO_WS" == 'true' ]]; then
   node_modules/.bin/http-server . &
 else
-  node_modules/.bin/live-server --no-browser . &
+  node_modules/.bin/live-server --no-browser --ignore=logs . &
 fi
 SERVER_PID="$!"
+trap "kill $SERVER_PID; set +m" EXIT
 sleep 2
 
-node_modules/.bin/phantomjs visit-site.js
-RESULT="$?"
-
-kill "$SERVER_PID"
-set +m
-
-exit "$RESULT"
+PHANTOMJS_CMD+=("$DEMO_ROOTDIR/visit-site.js")
+printf 'Running PhantomJS as: %s\n' "${PHANTOMJS_CMD[*]}"
+"${PHANTOMJS_CMD[@]}"
